//*Home Screen
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_FETCHED = 'PRODUCT_LIST_FETCHED'
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR'

//*Product Screen
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_FETCHED = 'PRODUCT_DETAILS_FETCHED'
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR'
